In [ ]:
!pip install scipy

In [ ]:
!pip install pandas matplotlib seaborn

## Rozkłady statystyczne

dokumentacja https://docs.scipy.org/doc/scipy/reference/stats.html

In [2]:
from scipy import stats

In [15]:
rozklad_norm = stats.norm().rvs(size=50)
rozklad_norm

array([ 0.22403321, -0.36123397,  0.13561827,  1.12581938,  0.35941715,
       -0.51521155, -1.40610025,  0.13457116, -0.15857418, -0.8988229 ,
        0.58702381,  1.1623275 , -0.71054786, -1.36298917, -0.07949301,
       -0.03726287,  0.69171715, -0.10397229, -0.55015719,  0.70631238,
       -1.61785229, -1.42538307,  2.02462462, -2.08583944, -1.5312037 ,
       -0.56991328,  1.45446337,  1.13302584, -1.23517275,  0.63801041,
        0.64757904,  0.29605558, -0.32068536,  0.89078641,  0.73190749,
       -1.59560051, -0.69144935, -1.49644491, -0.47423014, -0.27070376,
       -0.3545998 ,  1.39765414,  0.43970627, -0.71971126, -1.59751634,
        0.57143947,  0.82406594,  0.08367619, -1.63792569, -0.16921249])

In [13]:
rozklad_uni = stats.uniform().rvs(size=50)
rozklad_uni 

array([0.22976349, 0.08370756, 0.02327905, 0.76425617, 0.75702403,
       0.63034507, 0.24335952, 0.16709624, 0.3613958 , 0.20920549,
       0.33774633, 0.55889228, 0.61891784, 0.72628142, 0.00363037,
       0.29204238, 0.23726607, 0.99906931, 0.46402308, 0.31531279,
       0.54820671, 0.08146001, 0.10379809, 0.58526292, 0.28990816,
       0.13832067, 0.27499879, 0.7623766 , 0.47245733, 0.81760838,
       0.20452177, 0.97491827, 0.98640755, 0.73333098, 0.93102698,
       0.48092061, 0.29781206, 0.94631832, 0.40915106, 0.60520845,
       0.45964476, 0.68126124, 0.779518  , 0.89378417, 0.28506341,
       0.95432053, 0.82675508, 0.56408741, 0.28214585, 0.28137052])

In [25]:
rozklad_poisson = stats.poisson.rvs(mu=2, size=100)
rozklad_poisson

array([3, 0, 3, 3, 1, 1, 2, 4, 1, 4, 4, 2, 0, 1, 2, 1, 1, 0, 0, 1, 2, 2,
       3, 1, 2, 1, 1, 2, 2, 1, 4, 4, 4, 2, 2, 4, 2, 0, 1, 1, 0, 2, 2, 2,
       0, 3, 2, 2, 1, 0, 2, 1, 6, 3, 3, 2, 0, 1, 6, 2, 1, 2, 3, 2, 2, 0,
       2, 1, 1, 4, 5, 2, 2, 0, 1, 2, 4, 3, 0, 2, 3, 1, 4, 4, 3, 2, 3, 1,
       2, 4, 2, 2, 2, 3, 2, 1, 3, 2, 2, 2])

In [23]:
from collections import Counter

In [26]:
Counter(rozklad_poisson)

Counter({np.int64(2): 36,
         np.int64(1): 23,
         np.int64(3): 14,
         np.int64(0): 12,
         np.int64(4): 12,
         np.int64(6): 2,
         np.int64(5): 1})

In [27]:
Counter(rozklad_uni)

Counter({np.float64(0.2297634894222904): 1,
         np.float64(0.0837075568097817): 1,
         np.float64(0.023279051065152268): 1,
         np.float64(0.7642561721369155): 1,
         np.float64(0.7570240306073812): 1,
         np.float64(0.6303450705595491): 1,
         np.float64(0.2433595213358617): 1,
         np.float64(0.16709624357009578): 1,
         np.float64(0.3613957997232815): 1,
         np.float64(0.20920549147419043): 1,
         np.float64(0.3377463319116235): 1,
         np.float64(0.5588922825842741): 1,
         np.float64(0.6189178412732338): 1,
         np.float64(0.7262814157590708): 1,
         np.float64(0.0036303679334939165): 1,
         np.float64(0.29204237551620826): 1,
         np.float64(0.23726606609593404): 1,
         np.float64(0.999069310683586): 1,
         np.float64(0.4640230774087294): 1,
         np.float64(0.31531279383581956): 1,
         np.float64(0.5482067132584825): 1,
         np.float64(0.08146001067722852): 1,
         np.float64(0.

## Całkowanie

dokumentacja https://docs.scipy.org/doc/scipy/reference/integrate.html

In [28]:
from scipy import integrate

In [30]:
from math import sin

In [31]:
integrate.quad(a=0, b=3.1415, func=sin)

(1.9999999957076557, 2.2204460444848536e-14)

In [37]:
# definiowanie własnych funkcji
def parabola():
    # ciało funkcji - to co się ma dziać jak funkcja jest wywołana
    print("jestem teraz wewnątrz funkcji 'parabola'")


In [39]:
parabola()

jestem teraz wewnątrz funkcji 'parabola'


In [43]:
# funkcja z parametrem
def parabola_2(x):
    print(f"jestem teraz wewnątrz funkcji 'parabola_2', a podałeś x={x}")

In [44]:
parabola_2(5)

jestem teraz wewnątrz funkcji 'parabola_2', a podałeś x=5


In [46]:
parabola_2(100)

jestem teraz wewnątrz funkcji 'parabola_2', a podałeś x=100


In [58]:
# funkcja zwracająca wartość
def parabola_3(x, a, b, c):
    print(f"Podałeś: a={a}, b={b}, c={c}, x={x}")
    y = a*x**2 + b*x + c
    print(f"Wynik: y={y}")
    return y

In [59]:
parabola_3(a=1, b=0, c=0, x=6)

Podałeś: a=1, b=0, c=0, x=6
Wynik: y=36


36

In [60]:
integrate.quad(a=0, b=10, func=parabola_3, args=(1, 0, 0))

Podałeś: a=1, b=0, c=0, x=5.0
Wynik: y=25.0
Podałeś: a=1, b=0, c=0, x=0.13046735741414128
Wynik: y=0.017021731350629288
Podałeś: a=1, b=0, c=0, x=9.86953264258586
Wynik: y=97.40767458306782
Podałeś: a=1, b=0, c=0, x=0.6746831665550772
Wynik: y=0.45519737523278603
Podałeś: a=1, b=0, c=0, x=9.325316833444923
Wynik: y=86.96153404413124
Podałeś: a=1, b=0, c=0, x=1.6029521585048778
Wynik: y=2.569455622455447
Podałeś: a=1, b=0, c=0, x=8.397047841495123
Wynik: y=70.51041245235791
Podałeś: a=1, b=0, c=0, x=2.8330230293537637
Wynik: y=8.026019484848776
Podałeś: a=1, b=0, c=0, x=7.166976970646236
Wynik: y=51.365558897773504
Podałeś: a=1, b=0, c=0, x=4.255628305091844
Wynik: y=18.110372271098882
Podałeś: a=1, b=0, c=0, x=5.744371694908156
Wynik: y=32.997806169262
Podałeś: a=1, b=0, c=0, x=0.021714184870959663
Wynik: y=0.0004715058246102135
Podałeś: a=1, b=0, c=0, x=9.978285815129041
Wynik: y=99.56618780840543
Podałeś: a=1, b=0, c=0, x=0.34921254322145856
Wynik: y=0.12194940034319907
Podałeś: a=1,

(333.33333333333326, 3.700743415417188e-12)

## szukanie minimum funkcji

In [61]:
from scipy import optimize

In [66]:
opt = optimize.minimize_scalar(parabola_3, args=(1, 5, 15))
opt

Podałeś: a=1, b=5, c=15, x=0.0
Wynik: y=15.0
Podałeś: a=1, b=5, c=15, x=1.0
Wynik: y=21.0
Podałeś: a=1, b=5, c=15, x=-1.618034
Wynik: y=9.527864025156
Podałeś: a=1, b=5, c=15, x=-2.5
Wynik: y=8.75
Podałeś: a=1, b=5, c=15, x=-3.927050974844
Wynik: y=10.786474484803213
Podałeś: a=1, b=5, c=15, x=-3.0450849526572634
Wynik: y=9.047117605613373
Podałeś: a=1, b=5, c=15, x=-2.163118974844
Wynik: y=8.863488825110156
Podałeś: a=1, b=5, c=15, x=-2.49999996299
Wynik: y=8.750000000000002
Podałeś: a=1, b=5, c=15, x=-2.50000003701
Wynik: y=8.75
Podałeś: a=1, b=5, c=15, x=-2.7082039419001225
Wynik: y=8.793348881422748
Podałeś: a=1, b=5, c=15, x=-2.5000000740200004
Wynik: y=8.750000000000005


 message: 
          Optimization terminated successfully;
          The returned value satisfies the termination criteria
          (using xtol = 1.48e-08 )
 success: True
     fun: 8.75
       x: -2.50000003701
     nit: 6
    nfev: 11

In [68]:
opt.x, opt.fun

(np.float64(-2.50000003701), np.float64(8.75))

In [65]:
parabola_3(-2.5, 1, 5, 15)

Podałeś: a=1, b=5, c=15, x=-2.5
Wynik: y=8.75


8.75