In [1]:
!pip install numpy

In [2]:
import numpy as np

In [7]:
tablica = np.array( [1, 2.0, 3] )
tablica

array([1., 2., 3.])

In [8]:
np.array( ['a', 'bc', 'def'] )

array(['a', 'bc', 'def'], dtype='<U3')

In [9]:
np.array( [{'a': 1}, {'bc':41}, {'def':2141}] )

array([{'a': 1}, {'bc': 41}, {'def': 2141}], dtype=object)

In [10]:
tablica = np.array( [1, 2.0, 3] )
tablica

array([1., 2., 3.])

In [14]:
tablica[1]

np.float64(2.0)

In [13]:
print(tablica[1])

2.0


In [15]:
tablica[-1]

np.float64(3.0)

In [16]:
tablica[1:]

array([2., 3.])

In [17]:
lista = [1, 2, 3, 4, 5] 
tablica = np.array( lista )

In [18]:
lista

[1, 2, 3, 4, 5]

In [19]:
tablica

array([1, 2, 3, 4, 5])

In [24]:
lista * 5

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [21]:
['pizza'] * 10

['pizza',
 'pizza',
 'pizza',
 'pizza',
 'pizza',
 'pizza',
 'pizza',
 'pizza',
 'pizza',
 'pizza']

In [25]:
tablica * 5

array([ 5, 10, 15, 20, 25])

In [27]:
lista + lista

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [28]:
tablica + tablica

array([ 2,  4,  6,  8, 10])

In [29]:
tabl_a = np.array( [ 1, 2, 3] )
tabl_b = np.array( [ 4, 5, 6, 7] )

In [30]:
tabl_a + tabl_b

ValueError: operands could not be broadcast together with shapes (3,) (4,) 

In [34]:
tab_2d = np.array( [ (1,2,3), [4,5,6] ] )
tab_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [40]:
tab_3d = np.array(
    [
        [  [1, 2, 3], [4, 5, 6], [7, 8, 9] ],
        [  [10, 20, 30], [40, 50, 60], [70, 80, 90] ],
        [  [100, 200, 300], [400, 500, 600], [700, 800, 900] ],
    ]
    )
tab_3d

array([[[  1,   2,   3],
        [  4,   5,   6],
        [  7,   8,   9]],

       [[ 10,  20,  30],
        [ 40,  50,  60],
        [ 70,  80,  90]],

       [[100, 200, 300],
        [400, 500, 600],
        [700, 800, 900]]])

In [39]:
tab_3d.ndim

3

In [41]:
tab_2d.ndim

2

In [42]:
tab_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [44]:
tab_2d[ 0 , 0:2 ] 

array([1, 2])

In [46]:
tab_3d[ 0 , 0:2, 2 ] 

array([3, 6])

In [53]:
tab_3d[ 1, -1]

1

In [54]:
tab_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [55]:
tab_2d.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [58]:
tab_2d.shape

(2, 3)

In [59]:
tab_2d.T.shape

(3, 2)

In [61]:
tab_3d.size

27

In [65]:
tab_3d.flatten()

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  20,  30,  40,
        50,  60,  70,  80,  90, 100, 200, 300, 400, 500, 600, 700, 800,
       900])

In [66]:
tab_3d.T.flatten()

array([  1,  10, 100,   4,  40, 400,   7,  70, 700,   2,  20, 200,   5,
        50, 500,   8,  80, 800,   3,  30, 300,   6,  60, 600,   9,  90,
       900])

In [70]:
np.dot(tab_2d, tab_2d.T)

array([[14, 32],
       [32, 77]])

In [71]:
np.mean(tab_3d)

np.float64(185.0)

In [73]:
tab_3d[ 2, 1, 0 ] = 0
tab_3d

array([[[  1,   2,   3],
        [  4,   5,   6],
        [  7,   8,   9]],

       [[ 10,  20,  30],
        [ 40,  50,  60],
        [ 70,  80,  90]],

       [[100, 200, 300],
        [  0, 500, 600],
        [700, 800, 900]]])

In [75]:
np.zeros( (5, 5) )

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

## Zadanie

Przygotuj macierz z tabliczką mnożenia.

Hint:
- zrób macierz (array w numpy) 10x10 z samymi zerami
- przebiegnij w for po jednym wymiarze (range())
- w środku tego fora - przebignij for-em po drugim wymiarze
- w macierz na przecięciu wstaw wynik mnożenia indeksów z for-ów
- 

In [81]:
tabliczka_mnozenia = np.zeros( (10, 10), dtype=np.int8)
for x in range(1, 11):
    for y in range(1, 11):
        w = x * y
        tabliczka_mnozenia[x-1, y-1] = w 

tabliczka_mnozenia

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [  2,   4,   6,   8,  10,  12,  14,  16,  18,  20],
       [  3,   6,   9,  12,  15,  18,  21,  24,  27,  30],
       [  4,   8,  12,  16,  20,  24,  28,  32,  36,  40],
       [  5,  10,  15,  20,  25,  30,  35,  40,  45,  50],
       [  6,  12,  18,  24,  30,  36,  42,  48,  54,  60],
       [  7,  14,  21,  28,  35,  42,  49,  56,  63,  70],
       [  8,  16,  24,  32,  40,  48,  56,  64,  72,  80],
       [  9,  18,  27,  36,  45,  54,  63,  72,  81,  90],
       [ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100]], dtype=int8)

In [80]:
tabliczka_mnozenia.dtype

dtype('float64')